requireNamespace("readr")
requireNamespace("BeeDC")
requireNamespace("dplyr")


## existing data
db_standardized <- dplyr::tribble(
              ~decimalLatitude, ~decimalLongitude, ~recordNumber,                                  ~recordedBy, ~individualCount, ~samplingProtocol, ~associatedTaxa,     ~sex,      ~catalogNumber, ~institutionCode, ~otherCatalogNumbers, ~recordId,                          ~occurrenceID, ~collectionID,            ~genus, ~specificEpithet, ~id,                                                       ~locality, ~database_id,
                         2.233,              -90L,            NA,                              "James Ogilvie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323864",           "AMNH",                   NA,        NA, "85fb767f-1f99-482f-896c-69dce8b59097",            NA, "Pseudoanthidium",      "truncatum",  NA,                                                              NA,  "db_fake_1",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323581",           "AMNH",                   NA,        NA, "63f56ed1-7391-4814-a298-c1b67ca986be",            NA,        "Halictus",        "simplex",  NA,                                                 "near Weing Sa",  "db_fake_2",
                         2.233,              -90L,            NA, "T. D. A. Cockerell & Wilmatte P. Cockerell",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323583",           "AMNH",                   NA,        NA, "cde3718b-8621-4b3f-b203-4436961a4b73",            NA,        "Halictus",        "simplex",  NA, "Lake Waskesiu, at the beginning of the portage to Heart Lakes",  "db_fake_3",
                         2.233,              -90L,            NA,                              "C. S. Brimley",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00324010",           "AMNH",                   NA,        NA, "82e1eab7-5d92-4358-aede-1fab15ba4eda",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_4",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323630",           "AMNH",                   NA,        NA, "c161e78e-c091-4483-adf4-6b54045283d7",            NA,        "Halictus",        "simplex",  NA,                     "Prince Albert National Park, Lake Ajawaan",  "db_fake_5",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323584",           "AMNH",                   NA,        NA, "002a4861-5374-46ac-84d4-087762ba0c88",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_6",
                         2.233,              -90L,            NA,       "T. D. A. Cockerell & Alice M. Mackie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323616",           "AMNH",                   NA,        NA, "5e848030-8e9d-4f64-873d-08fee631e7dd",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_7",
                         2.233,              -90L,            NA,                            "Alice M. Mackie",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323619",           "AMNH",                   NA,        NA, "250ba041-2727-43d0-a39e-8d3470f5a8bf",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_8",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323591",           "AMNH",                   NA,        NA, "4cad3ea9-11b3-4589-b1d1-0035a84ea861",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_9",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323601",           "AMNH",                   NA,        NA, "dc3ebe14-f11f-45e9-b121-d34a8693284e",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_10",
                         2.233,              -90L,            NA,                                "A. H. Manes",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00324011",           "AMNH",                   NA,        NA, "6f1d8a81-3a4a-4650-be8c-7102f073e90e",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_11",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323627",           "AMNH",                   NA,        NA, "406433bc-9c08-4e94-9768-d8df0bdd92cb",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_12",
                         2.233,              -90L,            NA,                            "Alice M. Mackie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323611",           "AMNH",                   NA,        NA, "bf53740e-e96c-4b5a-a0e9-6b4bea3b2448",            NA,        "Halictus",        "simplex",  NA,                                        "Kaieteur National Park", "db_fake_13",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323613",           "AMNH",                   NA,        NA, "2e6d4df0-0a46-4837-b340-ed6f8166a831",            NA,        "Halictus",        "simplex",  NA,                                               "Kum Puang Creek", "db_fake_14",
                         2.233,              -90L,            NA,                            "Alice M. Mackie",               1L,                NA,              NA,       NA, "AMNH_IZC 00323617",           "AMNH",                   NA,        NA, "c0642780-37dc-4625-8a30-eacd5dbd1b70",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_15",
                         2.233,              -90L,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE",       "Fake_data_1",           "AMNH",                   NA,        NA, "259d5501-c49c-4a0b-99fc-1595ffe403b1",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_16",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_2",      "Bee Place",                   NA,        NA,                        "not_a_number1",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_17",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_3",      "Bee Place",                   NA,        NA,                        "not_a_number2",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_18",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_4",      "Bee Place",                   NA,        NA,                        "not_a_number3",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_19",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_5",      "Bee Place",                   NA,        NA,                        "not_a_number4",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_20",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_6",      "Bee Place",                   NA,        NA,                        "not_a_number5",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_21",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_7",      "Bee Place",                   NA,        NA,                        "not_a_number6",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_22",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_8",      "Bee Place",                   NA,        NA,                        "not_a_number7",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_23",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_9",      "Bee Place",                   NA,        NA,                        "not_a_number8",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_24",
                         2.233,              -90L,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,      "Fake_data_10",      "Bee Place",                   NA,        NA,                        "not_a_number9",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_25",
                         2.233,              -90L,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_11",      "Bee Place",                   NA,        NA,                       "not_a_number10",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_26",
                         2.233,              -90L,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_12",      "Bee Place",                   NA,        NA,                       "not_a_number11",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_27",
                         2.233,              -90L,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_13",      "Bee Place",                   NA,        NA,                       "not_a_number12",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_28",
                         2.233,              -90L,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_14",      "Bee Place",                   NA,        NA,                       "not_a_number13",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_29",
                         2.233,              -90L,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_15",      "Bee Place",                   NA,        NA,                       "not_a_number14",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_30"
              )




## Paige corrections - this is FAKED DATA AND SHOULD NOT BE USED FOR ANYTHING EVER OTHER THAN THIS TEST
PaigeNAm <- dplyr::tribble(
               ~decimalLatitude, ~decimalLongitude, ~recordNumber,          ~recordedBy, ~individualCount, ~samplingProtocol, ~associatedTaxa,     ~sex, ~catalogNumber, ~institutionCode, ~otherCatalogNumbers, ~recordId,                          ~occurrenceID, ~collectionID,           ~genus, ~specificEpithet, ~id,      ~locality, ~database_id,
                          2.233,               -90,            NA, "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE",  "Fake_data_1",           "AMNH",                   NA,        NA, "259d5501-c49c-4a0b-99fc-1595ffe403b1",            NA,       "Halictus",        "simplex",  NA,             NA, "db_fake_16",
                          2.233,                -90,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_2",      "Bee Place",                   NA,        NA,                        "not_a_number1",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_17",
                       9.370558,        -79.247071,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_3",      "Bee Place",                   NA,        NA,                        "not_a_number2",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_18",
                       9.370558,        -79.247071,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_4",      "Bee Place",                   NA,        NA,                        "not_a_number3",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_19",
                          2.233,                -90,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_5",      "Bee Place",                   NA,        NA,                        "not_a_number4",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_20",
                          2.233,                -90,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_6",      "Bee Place",                   NA,        NA,                        "not_a_number5",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_21",
                       9.370558,        -79.247071,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_7",      "Bee Place",                   NA,        NA,                        "not_a_number6",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_22",
                          2.233,                -90,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_8",      "Bee Place",                   NA,        NA,                        "not_a_number7",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_23",
                          2.233,                -90,            NA,         "Easter Egg",               NA,                NA,              NA,       NA,  "Fake_data_9",      "Bee Place",                   NA,        NA,                        "not_a_number8",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_24",
                       9.370558,        -79.247071,            NA,         "Easter Egg",               NA,                NA,              NA,       NA, "Fake_data_10",      "Bee Place",                   NA,        NA,                        "not_a_number9",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_25",
                          2.233,                -90,            NA,               "Nope",               NA,                NA,              NA,       NA, "Fake_data_11",      "Bee Place",                   NA,        NA,                       "not_a_number10",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_26",
                          2.233,                -90,            NA,               "Nope",               NA,                NA,              NA,       NA, "Fake_data_12",      "Bee Place",                   NA,        NA,                       "not_a_number11",            NA, "Augochloropsis",        "fulgida",  NA, "non-existent", "db_fake_27",
                          2.233,                -90,            NA,               "Nope",               NA,                NA,              NA,       NA, "Fake_data_13",      "Bee Place",                   NA,        NA,                       "not_a_number12",            NA,   "Lasioglossum",  "semicaeruleum",  NA, "non-existent", "db_fake_28",
                          2.233,                -90,            NA,               "Nope",               NA,                NA,              NA,       NA, "Fake_data_14",      "Bee Place",                   NA,        NA,                       "not_a_number13",            NA,   "Lasioglossum",  "semicaeruleum",  NA, "non-existent", "db_fake_29",
                          2.233,                -90,            NA,               "Nope",               NA,                NA,              NA,       NA, "Fake_data_15",      "Bee Place",                   NA,        NA,                       "not_a_number14",            NA,   "Lasioglossum",  "semicaeruleum",  NA, "non-existent", "db_fake_30"
               )



columnStrings <-  list(c("decimalLatitude", "decimalLongitude", 
                   "recordNumber", "recordedBy", "individualCount", "samplingProtocol",
                   "associatedTaxa", "sex", "catalogNumber", "institutionCode", "otherCatalogNumbers",
                   "recordId", "occurrenceID", "collectionID"), # Iteration 1
c("catalogNumber", "institutionCode", "otherCatalogNumbers",
  "recordId", "occurrenceID", "collectionID"), # Iteration 2
c("decimalLatitude", "decimalLongitude", 
  "recordedBy", "genus", "specificEpithet"), # Iteration 3
c("id", "decimalLatitude", "decimalLongitude"), # Iteration 4
c("recordedBy", "genus", "specificEpithet", "locality"), # Iteration 5
c("recordedBy", "institutionCode", "genus", 
  "specificEpithet","locality"),# Iteration 6
c("occurrenceID","decimalLatitude", "decimalLongitude"), # Iteration 7
c("catalogNumber","decimalLatitude", "decimalLongitude"), # Iteration 8
c("catalogNumber", "locality") # Iteration 9
)

## generate new data using function
testOut <- BeeDC::PaigeIntegrater(db_standardized = testData, PaigeNAm = paigeData, columnStrings = columnList)
                                   

## test the function

# the correct answer 
correct <- dplyr::tribble(
             ~decimalLatitude, ~decimalLongitude, ~recordNumber,                                  ~recordedBy, ~individualCount, ~samplingProtocol, ~associatedTaxa,     ~sex,      ~catalogNumber, ~institutionCode, ~otherCatalogNumbers, ~recordId,                          ~occurrenceID, ~collectionID,            ~genus, ~specificEpithet, ~id,                                                       ~locality, ~database_id,
                        2.233,               -90,            NA,                              "James Ogilvie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323864",           "AMNH",                   NA,        NA, "85fb767f-1f99-482f-896c-69dce8b59097",            NA, "Pseudoanthidium",      "truncatum",  NA,                                                              NA,  "db_fake_1",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323581",           "AMNH",                   NA,        NA, "63f56ed1-7391-4814-a298-c1b67ca986be",            NA,        "Halictus",        "simplex",  NA,                                                 "near Weing Sa",  "db_fake_2",
                        2.233,               -90,            NA, "T. D. A. Cockerell & Wilmatte P. Cockerell",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323583",           "AMNH",                   NA,        NA, "cde3718b-8621-4b3f-b203-4436961a4b73",            NA,        "Halictus",        "simplex",  NA, "Lake Waskesiu, at the beginning of the portage to Heart Lakes",  "db_fake_3",
                        2.233,               -90,            NA,                              "C. S. Brimley",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00324010",           "AMNH",                   NA,        NA, "82e1eab7-5d92-4358-aede-1fab15ba4eda",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_4",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323630",           "AMNH",                   NA,        NA, "c161e78e-c091-4483-adf4-6b54045283d7",            NA,        "Halictus",        "simplex",  NA,                     "Prince Albert National Park, Lake Ajawaan",  "db_fake_5",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323584",           "AMNH",                   NA,        NA, "002a4861-5374-46ac-84d4-087762ba0c88",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_6",
                        2.233,               -90,            NA,       "T. D. A. Cockerell & Alice M. Mackie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323616",           "AMNH",                   NA,        NA, "5e848030-8e9d-4f64-873d-08fee631e7dd",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_7",
                        2.233,               -90,            NA,                            "Alice M. Mackie",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323619",           "AMNH",                   NA,        NA, "250ba041-2727-43d0-a39e-8d3470f5a8bf",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_8",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323591",           "AMNH",                   NA,        NA, "4cad3ea9-11b3-4589-b1d1-0035a84ea861",            NA,        "Halictus",        "simplex",  NA,                                                              NA,  "db_fake_9",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA,   "MALE", "AMNH_IZC 00323601",           "AMNH",                   NA,        NA, "dc3ebe14-f11f-45e9-b121-d34a8693284e",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_10",
                        2.233,               -90,            NA,                                "A. H. Manes",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00324011",           "AMNH",                   NA,        NA, "6f1d8a81-3a4a-4650-be8c-7102f073e90e",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_11",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323627",           "AMNH",                   NA,        NA, "406433bc-9c08-4e94-9768-d8df0bdd92cb",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_12",
                        2.233,               -90,            NA,                            "Alice M. Mackie",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323611",           "AMNH",                   NA,        NA, "bf53740e-e96c-4b5a-a0e9-6b4bea3b2448",            NA,        "Halictus",        "simplex",  NA,                                        "Kaieteur National Park", "db_fake_13",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE", "AMNH_IZC 00323613",           "AMNH",                   NA,        NA, "2e6d4df0-0a46-4837-b340-ed6f8166a831",            NA,        "Halictus",        "simplex",  NA,                                               "Kum Puang Creek", "db_fake_14",
                        2.233,               -90,            NA,                            "Alice M. Mackie",               1L,                NA,              NA,       NA, "AMNH_IZC 00323617",           "AMNH",                   NA,        NA, "c0642780-37dc-4625-8a30-eacd5dbd1b70",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_15",
                        2.233,               -90,            NA,                         "T. D. A. Cockerell",               1L,                NA,              NA, "FEMALE",       "Fake_data_1",           "AMNH",                   NA,        NA, "259d5501-c49c-4a0b-99fc-1595ffe403b1",            NA,        "Halictus",        "simplex",  NA,                                                              NA, "db_fake_16",
                        2.233,               -90,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_2",      "Bee Place",                   NA,        NA,                        "not_a_number1",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_17",
                     9.370558,        -79.247071,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_3",      "Bee Place",                   NA,        NA,                        "not_a_number2",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_18",
                     9.370558,        -79.247071,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_4",      "Bee Place",                   NA,        NA,                        "not_a_number3",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_19",
                        2.233,               -90,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_5",      "Bee Place",                   NA,        NA,                        "not_a_number4",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_20",
                        2.233,               -90,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_6",      "Bee Place",                   NA,        NA,                        "not_a_number5",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_21",
                     9.370558,        -79.247071,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_7",      "Bee Place",                   NA,        NA,                        "not_a_number6",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_22",
                        2.233,               -90,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_8",      "Bee Place",                   NA,        NA,                        "not_a_number7",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_23",
                        2.233,               -90,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,       "Fake_data_9",      "Bee Place",                   NA,        NA,                        "not_a_number8",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_24",
                     9.370558,        -79.247071,            NA,                                 "Easter Egg",               NA,                NA,              NA,       NA,      "Fake_data_10",      "Bee Place",                   NA,        NA,                        "not_a_number9",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_25",
                        2.233,               -90,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_11",      "Bee Place",                   NA,        NA,                       "not_a_number10",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_26",
                        2.233,               -90,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_12",      "Bee Place",                   NA,        NA,                       "not_a_number11",            NA,  "Augochloropsis",        "fulgida",  NA,                                                  "non-existent", "db_fake_27",
                        2.233,               -90,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_13",      "Bee Place",                   NA,        NA,                       "not_a_number12",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_28",
                        2.233,               -90,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_14",      "Bee Place",                   NA,        NA,                       "not_a_number13",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_29",
                        2.233,               -90,            NA,                                       "Nope",               NA,                NA,              NA,       NA,      "Fake_data_15",      "Bee Place",                   NA,        NA,                       "not_a_number14",            NA,    "Lasioglossum",  "semicaeruleum",  NA,                                                  "non-existent", "db_fake_30"
             )

  
testthat::test_that("PaigeIntegrater revised datatable with correct values", {
    testthat::expect_equal(testOut, correct)
})

