requireNamespace("readr")
requireNamespace("tibble")
requireNamespace("BeeDC")
requireNamespace("dplyr")
library(dplyr) ## could not use %>% without loading as library


testData <- tibble::tribble(
                  ~id, ~institutionCode, ~collectionCode, ~ownerInstitutionCode,     ~basisOfRecord,                          ~occurrenceID, ~catalogNumber, ~otherCatalogNumbers,                                                                                                         ~higherClassification,   ~kingdom,      ~phylum,    ~class,        ~order,  ~family,        ~scientificName, ~taxonID, ~scientificNameAuthorship,     ~genus, ~subgenus, ~specificEpithet, ~verbatimTaxonRank, ~infraspecificEpithet, ~taxonRank, ~identifiedBy, ~dateIdentified, ~identificationReferences, ~identificationRemarks, ~taxonRemarks, ~identificationQualifier, ~typeStatus,          ~recordedBy, ~associatedCollectors, ~recordNumber, ~eventDate, ~year, ~month, ~day, ~startDayOfYear, ~endDayOfYear, ~verbatimEventDate, ~occurrenceRemarks,                           ~habitat, ~substrate, ~verbatimAttributes, ~fieldNumber, ~eventID, ~informationWithheld, ~dataGeneralizations, ~dynamicProperties, ~associatedOccurrences, ~associatedSequences, ~associatedTaxa, ~reproductiveCondition, ~establishmentMeans, ~cultivationStatus, ~lifeStage, ~sex, ~individualCount, ~preparations,        ~country, ~stateProvince,    ~county, ~municipality,                 ~locality, ~locationRemarks, ~localitySecurity, ~localitySecurityReason, ~decimalLatitude, ~decimalLongitude, ~geodeticDatum, ~coordinateUncertaintyInMeters, ~verbatimCoordinates, ~georeferencedBy, ~georeferenceProtocol, ~georeferenceSources, ~georeferenceVerificationStatus, ~georeferenceRemarks, ~minimumElevationInMeters, ~maximumElevationInMeters, ~minimumDepthInMeters, ~maximumDepthInMeters, ~verbatimDepth, ~verbatimElevation, ~disposition, ~language, ~recordEnteredBy,       ~modified, ~`sourcePrimaryKey-dbpk`, ~collID,                                       ~recordID,                                                                         ~references,
              637436L,            "ASU",   "BIO386-2020",                    NA, "HumanObservation", "bd5eea21-0995-45e6-b626-7a3cb361d878",             NA,                   NA,                   "Animalia|Arthropoda|Hexapoda|Insecta|Pterygota|Neoptera|Hymenoptera|Apocrita|Aculeata|Apoidea|Apidae|Apis", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",       "Apis mellifera",  235783L,          "Linnaeus, 1758",     "Apis",        NA,      "mellifera",                 NA,                    NA,  "Species",            NA,              NA,                        NA,                     NA,            NA,                       NA,          NA, "Melkonoff, Natalie",                    NA,            NA,  "9/26/20", 2020L,     9L,  26L,            270L,            NA,                 NA,                 NA, "On Asclepias angustifolia flower",         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 0L,         NA,   NA,               NA,            NA, "United States",      "Arizona", "Maricopa",            NA, "Desert Botanical Garden",               NA,                0L,                      NA,        33.460551,       -111.942522,        "WGS84",                            50L,                   NA,               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/26/20 16:14",                       NA,     23L, "urn:uuid:bd5eea21-0995-45e6-b626-7a3cb361d878", "https://serv.biokic.asu.edu/ecdysis/collections/individual/index.php?occid=637436",
              637531L,            "ASU",   "BIO386-2020",                    NA, "HumanObservation", "a19fa123-6f6f-4c2a-92c7-f2d8409873b1",             NA,                   NA,  "Animalia|Arthropoda|Hexapoda|Insecta|Pterygota|Neoptera|Hymenoptera|Apocrita|Aculeata|Apoidea|Apidae|Apinae|Bombini|Bombus", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Bombus vosneskenskii",  603453L,       "Radoszkowski 1862",   "Bombus",        NA,  "vosneskenskii",                 NA,                    NA,  "Species",            NA,              NA,                        NA,                     NA,            NA,                       NA,          NA,          "Ma, Janey",                    NA,            NA,  "9/21/20", 2020L,     9L,  21L,            265L,            NA,                 NA,      "Hymenoptera",                                 NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 0L,         NA,   NA,               NA,            NA, "United States",           "AZ", "Maricopa",            NA,                "Glendale",               NA,                0L,                      NA,          33.5771,          112.1906,             NA,                            50L,                   NA,               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/26/20 22:36",                       NA,     23L, "urn:uuid:a19fa123-6f6f-4c2a-92c7-f2d8409873b1", "https://serv.biokic.asu.edu/ecdysis/collections/individual/index.php?occid=637531",
              637539L,            "ASU",   "BIO386-2020",                    NA, "HumanObservation", "1d420150-ce0f-4510-bdf9-e65125621e43",             NA,                   NA, "Animalia|Arthropoda|Hexapoda|Insecta|Pterygota|Neoptera|Hymenoptera|Apocrita|Aculeata|Apoidea|Apidae|Xylocopinae|Xylocopini", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",             "Xylocopa",  204218L,         "Latreille, 1802", "Xylocopa",        NA,               NA,                 NA,                    NA,    "Genus",            NA,              NA,                        NA,                     NA,            NA,                       NA,          NA,          "Ma, Janey",                    NA,            NA,  "9/21/20", 2020L,     9L,  21L,            265L,            NA,                 NA,    "Hymenopterans",                                 NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 0L,         NA,   NA,               NA,            NA, "United States",      "Arizona", "Maricopa",            NA,                "Glendale",               NA,                0L,                      NA,          33.5771,           112.186,             NA,                            50L,                   NA,               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/26/20 22:51",                       NA,     23L, "urn:uuid:1d420150-ce0f-4510-bdf9-e65125621e43", "https://serv.biokic.asu.edu/ecdysis/collections/individual/index.php?occid=637539",
              637542L,            "ASU",   "BIO386-2020",                    NA, "HumanObservation", "c56b011d-70f7-4ee8-b0b9-f37a32fb5cd4",             NA,                   NA,                               "Animalia|Arthropoda|Hexapoda|Insecta|Pterygota|Neoptera|Hymenoptera|Apocrita|Aculeata|Apoidea", "Animalia", "Arthropoda", "Insecta", "Hymenoptera",       NA,         "Megachilidae",   91998L,                        NA,         NA,        NA,               NA,                 NA,                    NA,   "Family",            NA,              NA,                        NA,                     NA,            NA,                       NA,          NA,          "Ma, Janey",                    NA,            NA,  "9/24/20", 2020L,     9L,  24L,            268L,            NA,                 NA,      "Hymenoptera",                                 NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 0L,         NA,   NA,               NA,            NA, "United States",           "AZ", "Maricopa",            NA,                "Glendale",               NA,                0L,                      NA,          33.5771,           112.186,             NA,                            50L,                   NA,               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/26/20 22:53",                       NA,     23L, "urn:uuid:c56b011d-70f7-4ee8-b0b9-f37a32fb5cd4", "https://serv.biokic.asu.edu/ecdysis/collections/individual/index.php?occid=637542"
              )


# Save a temporary version of these data
readr::write_csv(testData, paste0(tempdir(), "/testData.csv"))


testOut1 <- BeeDC::readr_Ecd(path = paste0(tempdir()),
                              inFile = "/testData.csv",
                              outFile = "testDataOut.csv",
                              dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")


# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)


# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_Ecd results columns TRUE", {
  testthat::expect_equal(resultsT, 53)
})

testthat::test_that("readr_Ecd results columns FALSE", {
  testthat::expect_equal(resultsF, 43)
})

testthat::test_that("readr_Ecd expected class", {
  testthat::expect_type(testOut1, "list")
})
