requireNamespace("readr")
requireNamespace("BeeDC")
requireNamespace("openxlsx")
requireNamespace("dplyr")
library(dplyr) ## could not use %>% without loading as library


testData <- dplyr::tribble(
                                 ~id,            ~type, ~institutionID, ~collectionID, ~institutionCode,                              ~collectionCode,          ~datasetName,      ~basisOfRecord,          ~occurrenceID, ~catalogNumber, ~occurrenceRemarks, ~recordedBy, ~organismQuantity, ~organismQuantityType, ~sex, ~lifeStage, ~preparations, ~associatedTaxa, ~previousIdentifications, ~samplingProtocol, ~eventDate, ~year, ~month, ~day, ~verbatimEventDate,            ~habitat, ~continent,   ~country, ~countryCode, ~stateProvince,          ~county,                                        ~locality,                    ~verbatimLocality, ~verbatimElevation, ~minimumElevationInMeters, ~maximumElevationInMeters, ~verbatimCoordinates, ~verbatimLatitude, ~verbatimLongitude, ~decimalLatitude, ~decimalLongitude, ~geodeticDatum, ~coordinateUncertaintyInMeters,               ~georeferencedBy, ~georeferencedDate,                                                                                                                                                                                                                                                                                                                                                                              ~georeferenceProtocol,                                                                                                                                                                                                                                                                                                                                    ~georeferenceSources,                                                                                                                                                                                 ~georeferenceRemarks, ~identifiedBy, ~dateIdentified, ~identificationRemarks, ~identificationQualifier, ~scientificName,   ~kingdom,      ~phylum,    ~class,        ~order,  ~family,     ~genus, ~subgenus, ~specificEpithet, ~infraspecificEpithet, ~taxonRank, ~verbatimTaxonRank, ~scientificNameAuthorship, ~taxonomicStatus,
               "COMFENALCO:MEPB:955", "Objeto fÃ.sico",  "890900842-6",     "RNC:147",     "COMFENALCO", "Museo EntomolÃ³gico Piedras Blancas (MEPB)", "ColecciÃ³n INDERENA", "PreservedSpecimen",  "COMFENALCO:MEPB:955",           955L,                 NA, "P Cardona",                1L,          "Individuos",   NA,   "Adulto",        "Seco",              NA,                 "Apidae",                NA,     "2002", 2002L,     NA,   NA,             "2002",          "Hotel***",       "SA", "Colombia",         "CO",     "QuindÃ.o",       "Quimbaya",           "Vereda Kerman, Km 7 al Parque Panaca", "Vereda Kerman, Km 7, Parque Panaca",      "1339 - 1339",                     1182L,                     1182L,                   NA,                NA,                 NA,          4.60781,         -75.82079,        "WGS84",                            671, "Daniel Suarez (SiB Colombia)",           "4/1/17", "Escobar D, Jojoa LM, DÃ.az SR, Rudas E, AlbarracÃ.n RD, RamÃ.rez C, GÃ³mez JY, LÃ³pez CR, Saavedra J, Ortiz R, (2016). GeorreferenciaciÃ³n de localidades: Una guÃ.a de referencia para colecciones biolÃ³gicas. Instituto de InvestigaciÃ³n de Recursos BiolÃ³gicos Alexander von Humboldt â€“ Instituto de Ciencias Naturales, Universidad Nacional de Colombia. BogotÃ¡ D.C., Colombia. 144 p", "Plancha 224 del Instituto GeogrÃ¡fico AgustÃ.n Codazzi - IGAC. Base cartogrÃ¡fica oficial integrada.Escala 1:100.000. CodificaciÃ³n de la divisiÃ³n polÃ.tico administrativa de Colombia(Divipola) - DANE. NASA Land Processes Distributed Active Archive Center (LP DAAC). ASTER Global DEM. EOSDIS/Reverb ECHO. https://reverb.echo.nasa.gov. 2011.",                                         "Nivel 2. Se valida la localidad. Se valida la geografÃ.a superior. No reporta coordenadas. Incertidumbre por extensiÃ³n de la localidad y escala del mapa.",            NA,              NA,                     NA,                       NA,        "Apidae", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",         NA,        NA,               NA,                    NA,  "Familia",              "sp.",                        NA,               NA,
              "COMFENALCO:MEPB:7534", "Objeto fÃ.sico",  "890900842-6",     "RNC:147",     "COMFENALCO", "Museo EntomolÃ³gico Piedras Blancas (MEPB)",           "DonaciÃ³n", "PreservedSpecimen", "COMFENALCO:MEPB:7534",          7534L,                 NA, "P Cardona",                1L,          "Individuos",   NA,   "Adulto",        "Seco",              NA,                 "Apidae",  "Captura manual",     "2002", 2002L,     NA,   NA,             "2002", "Intradomicilio***",       "SA", "Colombia",         "CO",     "QuindÃ.o",       "Quimbaya", "Parque Panaca, Km 7 de la vereda Kerman, hotel",  "Panaca, Km 7 Vereda Kerman, Hotel",                 NA,                     1182L,                     1182L,                   NA,                NA,                 NA,          4.60948,          -75.8252,        "WGS84",                            296, "Daniel Suarez (SiB Colombia)",           "4/1/17", "Escobar D, Jojoa LM, DÃ.az SR, Rudas E, AlbarracÃ.n RD, RamÃ.rez C, GÃ³mez JY, LÃ³pez CR, Saavedra J, Ortiz R, (2016). GeorreferenciaciÃ³n de localidades: Una guÃ.a de referencia para colecciones biolÃ³gicas. Instituto de InvestigaciÃ³n de Recursos BiolÃ³gicos Alexander von Humboldt â€“ Instituto de Ciencias Naturales, Universidad Nacional de Colombia. BogotÃ¡ D.C., Colombia. 144 p", "Plancha 224 del Instituto GeogrÃ¡fico AgustÃ.n Codazzi - IGAC. Base cartogrÃ¡fica oficial integrada.Escala 1:100.000. CodificaciÃ³n de la divisiÃ³n polÃ.tico administrativa de Colombia(Divipola) - DANE. NASA Land Processes Distributed Active Archive Center (LP DAAC). ASTER Global DEM. EOSDIS/Reverb ECHO. https://reverb.echo.nasa.gov. 2011.",                                         "Nivel 2. Se valida la localidad. Se valida la geografÃ.a superior. No reporta coordenadas. Incertidumbre por extensiÃ³n de la localidad y escala del mapa.",            NA,              NA,                     NA,                       NA,        "Apidae", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",         NA,        NA,               NA,                    NA,  "Familia",              "sp.",                        NA,               NA,
              "COMFENALCO:MEPB:1175", "Objeto fÃ.sico",  "890900842-6",     "RNC:147",     "COMFENALCO", "Museo EntomolÃ³gico Piedras Blancas (MEPB)", "ColecciÃ³n INDERENA", "PreservedSpecimen", "COMFENALCO:MEPB:1175",          1175L,                 NA,          NA,                1L,          "Individuos",   NA,   "Adulto",        "Seco",              NA,               "Xylocopa",                NA,   "7/1/83", 1983L,     7L,   1L,           "7/1/83",                  NA,       "SA", "Colombia",         "CO",    "Antioquia",          "Urrao",                                      "Sin Datos",                                   NA,                 NA,                     2250L,                     2250L,                   NA,                NA,                 NA,      6.337984698,       -76.2756657,        "WGS84",                      426237168,             "Ricardo Ortiz G.",          "6/12/16", "Escobar D, Jojoa LM, DÃ.az SR, Rudas E, AlbarracÃ.n RD, RamÃ.rez C, GÃ³mez JY, LÃ³pez CR, Saavedra J, Ortiz R, (2016). GeorreferenciaciÃ³n de localidades: Una guÃ.a de referencia para colecciones biolÃ³gicas. Instituto de InvestigaciÃ³n de Recursos BiolÃ³gicos Alexander von Humboldt â€“ Instituto de Ciencias Naturales, Universidad Nacional de Colombia. BogotÃ¡ D.C., Colombia. 144 p",   "Instituto GeogrÃ¡fico AgustÃ.n Codazzi - IGAC. Base cartogrÃ¡fica oficial integrada. Plancha 145. Escala 1:100.000. CodificaciÃ³n de la divisiÃ³n polÃ.tico administrativa de Colombia(Divipola) - DANE. NASA Land Processes Distributed Active Archive Center (LP DAAC). ASTER Global DEM. EOSDIS/Reverb ECHO. https://reverb.echo.nasa.gov. 2011.", "Nivel 4. Georreferenciado en el centroide del municipio. La incertidumbre corresponde a la distancia desde el centroide hasta el lÃ.mite mas alejado del municipio mas la incertidumbre por escala",            NA,              NA,                     NA,                       NA,      "Xylocopa", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Xylocopa",        NA,               NA,                    NA,  "GÃ©nero",              "sp.",         "Latreille, 1802",       "Aceptado",
              "COMFENALCO:MEPB:7531", "Objeto fÃ.sico",  "890900842-6",     "RNC:147",     "COMFENALCO", "Museo EntomolÃ³gico Piedras Blancas (MEPB)",           "DonaciÃ³n", "PreservedSpecimen", "COMFENALCO:MEPB:7531",          7531L,                 NA, "A Acevedo",                1L,          "Individuos",   NA,   "Adulto",        "Seco",              NA,                 "Apidae",            "Jama",   "3/1/84", 1984L,     3L,   1L,           "3/1/84",                  NA,       "SA", "Colombia",         "CO",    "Antioquia", "Puerto Triunfo",                                      "Sin Datos",                                   NA,                 NA,                      167L,                      167L,                   NA,                NA,                 NA,      5.953695157,      -74.68633006,        "WGS84",                      180120452,             "Ricardo Ortiz G.",          "6/12/16", "Escobar D, Jojoa LM, DÃ.az SR, Rudas E, AlbarracÃ.n RD, RamÃ.rez C, GÃ³mez JY, LÃ³pez CR, Saavedra J, Ortiz R, (2016). GeorreferenciaciÃ³n de localidades: Una guÃ.a de referencia para colecciones biolÃ³gicas. Instituto de InvestigaciÃ³n de Recursos BiolÃ³gicos Alexander von Humboldt â€“ Instituto de Ciencias Naturales, Universidad Nacional de Colombia. BogotÃ¡ D.C., Colombia. 144 p",   "Instituto GeogrÃ¡fico AgustÃ.n Codazzi - IGAC. Base cartogrÃ¡fica oficial integrada. Plancha 168. Escala 1:100.000. CodificaciÃ³n de la divisiÃ³n polÃ.tico administrativa de Colombia(Divipola) - DANE. NASA Land Processes Distributed Active Archive Center (LP DAAC). ASTER Global DEM. EOSDIS/Reverb ECHO. https://reverb.echo.nasa.gov. 2011.", "Nivel 4. Georreferenciado en el centroide del municipio. La incertidumbre corresponde a la distancia desde el centroide hasta el lÃ.mite mas alejado del municipio mas la incertidumbre por escala",            NA,              NA,                     NA,                       NA,        "Apidae", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",         NA,        NA,               NA,                    NA,  "Familia",              "sp.",                        NA,               NA
              ) %>%
  dplyr::mutate(year = year %>% as.double(),
                month = month %>% as.double(),
                day = day %>% as.double())

# Be sure that the testData is not already in tempdir
testDataPath <- file.info(list.files(tempdir(), full.names = T, 
                                     pattern = "testData.xlsx", recursive = TRUE))
unlink(rownames(testDataPath))

# Save a temporary version of these data
openxlsx::write.xlsx(testData, paste0(tempdir(), "/testData.xlsx"),
                 sheetName = "PiedrasBalncas Bees Data")


testOut1 <- BeeDC::readr_MEPB(path = paste0(tempdir()),
                            inFile = "/testData.xlsx",
                            outFile = "testDataOut.csv",
                            sheet = "PiedrasBalncas Bees Data",
                            dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")


# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)


# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_MEPB results columns TRUE", {
  testthat::expect_equal(resultsT, 46)
})

testthat::test_that("readr_MEPB results columns FALSE", {
  testthat::expect_equal(resultsF, 24)
})

testthat::test_that("readr_MEPB expected class", {
  testthat::expect_type(testOut1, "list")
})
