requireNamespace("readr")
requireNamespace("BeeDC")
requireNamespace("dplyr")

library(dplyr) ## could not use %>% without loading as library


testData <- dplyr::tribble(
                   ~basisOfRecord, ~catalogNumber, ~recordNumber,   ~locationID,      ~family,  ~subfamily,         ~genus, ~specificEpithet,           ~scientificName, ~identifiedBy,    ~sex, ~individualCount, ~decimalLatitude, ~decimalLongitude, ~elevationInMeters, ~stateOrProvince,        ~locality,   ~eventDate, ~eventTime, ~recordedBy,    ~country,                                                                                                                                                                                                                                                                                                               ~fieldNotes, ~samplingEffort,            ~associatedTaxa, ~Plant.ID.by, ~Plant.ID.using,                                                                                                                                                                                ~references, ~coordinateUncertaintyInMeters, ~institutionCode,                                                                                                                                                                     ~bibliographicCitation,
              "preservedSpecimen",             NA, "18JDEC450-A", "JBD_Site365", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey",     "F",               1L,        -17.26785,         145.49384,               868L,            "QLD", "Hallorans Hill",     "3/2/19",     "8:55",  "JB Dorey", "Australia",                                                                                                                                                                                                                                                    "Sight-swept off vegetation on rainforests edge. Mostly overcast ~24C",              NA, "Brachychiton acerifolius",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",
              "preservedSpecimen",             NA, "18JDEC459-A", "JBD_Site365", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey",    "2M",               2L,        -17.26761,         145.49474,               864L,            "QLD", "Hallorans Hill",     "5/2/19",    "12:12",  "JB Dorey", "Australia",                                                                                                                             "General sweep off Stenocarpus sinuatus 6-7 m up in the canopy of rainforest (probably regenerated around a remnant core). Partly sunny to raining. Other floral resources presented ~26C +i",    "15 minutes",     "Stenocarpus sinuatus",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",
              "preservedSpecimen",             NA,   "18JDEC460", "JBD_Site365", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey",    "2M",               2L,        -17.26761,         145.49474,               864L,            "QLD", "Hallorans Hill",     "5/2/19",    "14:30",  "JB Dorey", "Australia",                                                                                                                                           "General sweep off Stenocarpus sinuatus 6-7 m up in the canopy of rainforest (probably regenerated around a remnant core). Overcast. Other floral resources presented  ~26C +i",    "17 minutes",     "Stenocarpus sinuatus",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",
              "preservedSpecimen",             NA, "18JDEC497-A", "JBD_Site365", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey",     "M",               1L,        -17.26761,         145.49474,               864L,            "QLD", "Hallorans Hill",     "3/2/19",    "11:01",  "JB Dorey", "Australia",              "General/sight swept off Stenocarpus sinuatus. Males of Pharohylaeus frequently seen patrolling flowers ~slowly flying around each flower in what appeared to be a circuit. They would sometimes alight on leaves. No females were seen (or were at least caught) despite male activity. Hot and sunny ~30C",    "52 minutes",     "Stenocarpus sinuatus",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",
              "preservedSpecimen",             NA,    "19JDEC60", "JBD_Site380", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey", "4M 1F",               5L,        -16.81119,         145.63464,               351L,            "QLD",        "Kuranda", "20/11/2019",    "11:53",  "JB Dorey", "Australia",                                                                                                                                                  "Tall flame tree (~13 m high) on street surrounded by rainforest. Several females and males observed. Bees seen almost immediately upon arrival. Sunny and warm ~30C +i",    "14 minutes", "Brachychiton acerifolius",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",
              "preservedSpecimen",             NA,    "19JDEC61", "JBD_Site365", "Colletidae", "Hylaeinae", "Pharohylaeus",     "lactiferus", "Pharohylaeus lactiferus",    "JB Dorey", "1M 2F",               3L,        -17.26804,         145.49175,               853L,            "QLD",       "Atherton", "21/11/2019",    "10:30",  "JB Dorey", "Australia", "General sweep of flame tree near rainforest, but on a street. Males and females seen in flowers, but Hylaeinae have pollen covering their backs. Sunny and hot ~27C +i. Additionally: Lasioglossum sp. female, Tetragonula female, Meroglossa itamuca males and females, 3 Hylaeus (Gnathoprosopis) albonitens females.",    "14 minutes", "Brachychiton acerifolius",   "JB Dorey",       "Keybase", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180.",                            10L,          "Dorey", "DOREY, J. B. 2021. Missing for almost 100 years: the rare and potentially threatened bee Pharohylaeus lactiferus (Hymenoptera, Colltidae). Journal of Hymenoptera Research, 81, 165-180."
              )


# Save a temporary version of these data
readr::write_csv(testData, paste0(tempdir(), "/testData.csv"))

testOut1 <- BeeDC::readr_Dor(path = paste0(tempdir()),
                               inFile = "/testData.csv",
                               outFile = "testDataOut.csv",
                               dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")


# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)


# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_Dor results columns TRUE", {
  testthat::expect_equal(resultsT, 34)
})

testthat::test_that("readr_Dor results columns FALSE", {
  testthat::expect_equal(resultsF, 4)
})

testthat::test_that("readr_Dor expected class", {
  testthat::expect_type(testOut1, "list")
})
