requireNamespace("readr")
requireNamespace("BeeDC")
requireNamespace("dplyr")
library(dplyr) ## could not use %>% without loading as library


testData <- dplyr::tribble(
                   ~id, ~institutionCode, ~collectionCode, ~ownerInstitutionCode,      ~basisOfRecord, ~occurrenceID,  ~catalogNumber, ~otherCatalogNumbers,                                                                                      ~higherClassification,   ~kingdom,      ~phylum,    ~class,        ~order,  ~family,       ~scientificName, ~taxonID, ~scientificNameAuthorship,      ~genus, ~subgenus, ~specificEpithet, ~verbatimTaxonRank, ~infraspecificEpithet, ~taxonRank,             ~identifiedBy, ~dateIdentified, ~identificationReferences, ~identificationRemarks, ~taxonRemarks, ~identificationQualifier, ~typeStatus,                    ~recordedBy, ~associatedCollectors, ~recordNumber, ~eventDate, ~year, ~month, ~day, ~startDayOfYear, ~endDayOfYear, ~verbatimEventDate,                                                                                                                             ~occurrenceRemarks, ~habitat, ~substrate, ~verbatimAttributes, ~fieldNumber, ~eventID, ~informationWithheld, ~dataGeneralizations, ~dynamicProperties, ~associatedOccurrences, ~associatedSequences, ~associatedTaxa, ~reproductiveCondition, ~establishmentMeans, ~cultivationStatus, ~lifeStage,     ~sex, ~individualCount, ~preparations,        ~country, ~stateProvince,   ~county, ~municipality,                                                                             ~locality, ~locationRemarks, ~localitySecurity, ~localitySecurityReason, ~decimalLatitude, ~decimalLongitude, ~geodeticDatum, ~coordinateUncertaintyInMeters,                  ~verbatimCoordinates, ~georeferencedBy, ~georeferenceProtocol, ~georeferenceSources, ~georeferenceVerificationStatus, ~georeferenceRemarks, ~minimumElevationInMeters, ~maximumElevationInMeters, ~minimumDepthInMeters, ~maximumDepthInMeters, ~verbatimDepth, ~verbatimElevation, ~disposition, ~language, ~recordEnteredBy,       ~modified, ~`sourcePrimaryKey-dbpk`, ~collID,                                       ~recordID,                                                                         ~references,
              2109207L,           "FSCA",          "FSCA",                    NA, "PreservedSpecimen",            NA, "FSCA 00008737",                   NA, "Organism|Animalia|Arthropoda|Insecta|Hymenoptera|Apoidea|Anthophila|Apidae|Apinae|Anthophorini|Habropoda", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Habropoda laboriosa",   11043L,       "(Fabricius, 1804)", "Habropoda",        NA,      "laboriosa",                 NA,                    NA,  "Species", "Wiley, J. R. (James R.)",        "3/1/99",                        NA,  "Habropoda laboriosa",            NA,                       NA,          NA,    "Stange, L. A. (Lionel A.)",                    NA,            NA,  "3/25/91", 1991L,     3L,  25L,             84L,            NA,                 NA, "[Florida Alachua Co: Gainesvile Doyle Conner Bld, March 25, 1991 L.A. Stange col.] [Habropoda laboriosa (Fabricius) 1804 det. J. Wiley 1999]",       NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 NA,    "adult", "Female",               NA,            NA, "United States",      "Florida", "Alachua",            NA, "Doyle Conner Bldg. (32601), Dept. of Agriculture, Gainesville, Alachua Co., Florida",               NA,                0L,                      NA,         29.63438,         -82.37143,             NA,                             NA,                 "29.63438, -82.37143",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/12/22 14:58",          "FSCA 00008737",     14L, "urn:uuid:b08fcc6e-ba5d-437a-ba80-0ab32bfd0269", "https://library.big-bee.net/portal/collections/individual/index.php?occid=2109207",
              2109208L,           "FSCA",          "FSCA",                    NA, "PreservedSpecimen",            NA, "FSCA 00008738",                   NA, "Organism|Animalia|Arthropoda|Insecta|Hymenoptera|Apoidea|Anthophila|Apidae|Apinae|Anthophorini|Habropoda", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Habropoda laboriosa",   11043L,       "(Fabricius, 1804)", "Habropoda",        NA,      "laboriosa",                 NA,                    NA,  "Species",               "Wiley, J.",        "3/1/99",                        NA,  "Habropoda laboriosa",            NA,                       NA,          NA, "Weems Jr., H. V. (Howard V.)",                    NA,            NA,  "3/26/84", 1984L,     3L,  26L,             86L,            NA,                 NA, "[Florida Alachua Co., 8 miles W of Gainesville of FL 26 -111-1984 H.V. Weems, Jr.] [Habropoda laboriosa (Fabricius) 1804 det. J. Wiley 1999]",       NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 NA,    "adult",   "Male",               NA,            NA, "United States",      "Florida", "Alachua",            NA,                                             "8 mi. W of Gainesville, Alachua Co., FL",               NA,                0L,                      NA,      29.66733333,      -82.53688889,             NA,                             NA, "29.6673333333333, -82.5368888888889",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/12/22 14:58",          "FSCA 00008738",     14L, "urn:uuid:342bc796-8184-4f59-a8b2-1c68a9f67456", "https://library.big-bee.net/portal/collections/individual/index.php?occid=2109208",
              2109209L,           "FSCA",          "FSCA",                    NA, "PreservedSpecimen",            NA, "FSCA 00008739",                   NA, "Organism|Animalia|Arthropoda|Insecta|Hymenoptera|Apoidea|Anthophila|Apidae|Apinae|Anthophorini|Habropoda", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Habropoda laboriosa",   11043L,       "(Fabricius, 1804)", "Habropoda",        NA,      "laboriosa",                 NA,                    NA,  "Species",               "Wiley, J.",        "3/1/99",                        NA,  "Habropoda laboriosa",            NA,                       NA,          NA,                             NA,                    NA,            NA,  "3/17/85", 1985L,     3L,  17L,             76L,            NA,                 NA,                          "[Florida: Gainesville UF Campus Mtrap Bamila 17-III-1985] [Habropoda laboriosa (Fabricius) 1804 det. J. Wiley 1999]",       NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 NA,    "adult",   "Male",               NA,            NA, "United States",      "Florida", "Alachua",            NA,                                      "Gainesville, University of FL, Alachua Co., FL",               NA,                0L,                      NA,         29.65163,         -82.32483,             NA,                             NA,                 "29.65163, -82.32483",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/12/22 14:58",          "FSCA 00008739",     14L, "urn:uuid:af32f90c-2763-4a21-8f90-e93588a80c0f", "https://library.big-bee.net/portal/collections/individual/index.php?occid=2109209",
              2109210L,           "FSCA",          "FSCA",                    NA, "PreservedSpecimen",            NA, "FSCA 00008740",                   NA, "Organism|Animalia|Arthropoda|Insecta|Hymenoptera|Apoidea|Anthophila|Apidae|Apinae|Anthophorini|Habropoda", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Habropoda laboriosa",   11043L,       "(Fabricius, 1804)", "Habropoda",        NA,      "laboriosa",                 NA,                    NA,  "Species",               "Wiley, J.",        "3/1/99",                        NA,  "Habropoda laboriosa",            NA,                       NA,          NA,                             NA,                    NA,            NA,  "3/17/85", 1985L,     3L,  17L,             76L,            NA,                 NA,                          "[Florida: Gainesville UF Campus Mtrap Bamila 17-III-1985] [Habropoda laboriosa (Fabricius) 1804 det. J. Wiley 1999]",       NA,         NA,                  NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,                 NA,    "adult",   "Male",               NA,            NA, "United States",      "Florida", "Alachua",            NA,                                      "Gainesville, University of FL, Alachua Co., FL",               NA,                0L,                      NA,         29.65163,         -82.32483,             NA,                             NA,                 "29.65163, -82.32483",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "9/12/22 14:58",          "FSCA 00008740",     14L, "urn:uuid:ca52acc1-7026-46cd-8089-add7f4388734", "https://library.big-bee.net/portal/collections/individual/index.php?occid=2109210"
              )


# Save a temporary version of these data
readr::write_csv(testData, paste0(tempdir(), "/testData.csv"))


testOut1 <- BeeDC::readr_FSCA(path = paste0(tempdir()),
                              inFile = "/testData.csv",
                              outFile = "testDataOut.csv",
                              dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")


# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)


# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_FSCA results columns TRUE", {
  testthat::expect_equal(resultsT, 52)
})

testthat::test_that("readr_FSCA results columns FALSE", {
  testthat::expect_equal(resultsF, 0)
})

testthat::test_that("readr_FSCA expected class", {
  testthat::expect_type(testOut1, "list")
})
