requireNamespace("openxlsx")
requireNamespace("readr")
requireNamespace("tibble")
requireNamespace("dplyr")


testData <- tibble::tribble(
           ~database_id,                              ~scientificName,      ~family,   ~subfamily,          ~genus, ~subgenus, ~subspecies,                     ~species, ~specificEpithet, ~infraspecificEpithet, ~acceptedNameUsage, ~taxonRank, ~scientificNameAuthorship,      ~continent,        ~country, ~country_suggested, ~countryCode, ~stateProvince,         ~county, ~municipality,                                                                   ~locality, ~island,                                             ~license,                                                                                                     ~issue,             ~eventDate, ~day, ~month, ~year,       ~basisOfRecord,            ~type, ~occurrenceStatus, ~recordNumber,                      ~recordedBy, ~eventID, ~samplingProtocol, ~samplingEffort, ~individualCount,                  ~catalogNumber, ~rightsHolder, ~institutionCode, ~decimallatitude, ~decimallongitude, ~datasetID, ~datasetName, ~otherCatalogNumbers,                                                          ~occurrenceID, ~coreid,                                       ~recordId,                          ~collectionID,                             ~verbatimScientificName,      ~verbatimEventDate,           ~sex,                                          ~rights, ~occurrenceYear,           ~id,       ~dataSource,                 ~names_clean,                     ~verbatim_scientificName, ~geolocate_Latitude, ~geolocate_Longitude, ~geolocate_UncertaintyRadiusMeters, ~geolocate_Score, ~geolocate_Precision,                  ~geolocate_ParsePattern, ~geolocate_locFieldUsed, ~geolocate_NumResults,
       "Ecd_data_20840",          "Agapostemon texanus Cresson, 1872", "Halictidae", "Halictinae",   "Agapostemon",        NA,          NA,        "Agapostemon texanus",        "texanus",                    NA,                 NA,  "Species",           "Cresson, 1872",              NA, "United states",    "United states",         "US",   "California", "Santa Barbara",            NA,                                   "University of California, Santa Barbara",      NA, "https://creativecommons.org/licenses/by-nc-sa/4.0/",                                                                                                         NA, "1984-05-17T00:00:00Z",  17L,     5L, 1984L,  "PreservedSpecimen",               NA,                NA,            NA,                               NA,       NA,                NA,              NA,               1L,              "UCSB-IZC00005603",            NA,           "UCSB",               NA,                NA,         NA,           NA,                   NA,                                 "3de7811e-1169-4fe9-a451-59ba9c653449",      NA,                                              NA,                                     NA,                                                  NA,             "17/5/1984",         "Male",                                               NA,              NA, "UCSB_828348",  "Ecd_Anthophila",                           NA,          "Agapostemon texanus Cresson, 1872",           34.416323,          -119.846392,                                84L,             100L,               "High", "UNIVERSITY OF CALIFORNIA SANTA BARBARA",              "locality",                   15L,
    "Dorey_data_761973",       "Perdita trifasciata Timberlake, 1953", "Andrenidae", "Panurginae",       "Perdita",        NA,          NA,        "Perdita trifasciata",    "trifasciata",                    NA,                 NA,  "SPECIES",        "Timberlake, 1953",              NA, "United states",    "United states",         "US",   "New mexico",              NA,            NA,                                                         "Cottonwood Spring",      NA,                                            "CC0_1_0",                                                         "OCCURRENCE_STATUS_INFERRED_FROM_INDIVIDUAL_COUNT", "1990-09-03T00:00:00Z",   3L,     9L, 1990L,  "MATERIAL_CITATION",               NA,         "PRESENT",            NA, "T. L. Griswold & Walnut Canyon",       NA,                NA,              NA,               1L,                              NA,            NA,               NA,               NA,                NA,         NA,           NA,                   NA, "03DA51566E5A3810FF43FF7FFDD46C19.mc.3B1BEA1D6E583810FC56FF08FC936808",      NA,                                              NA,                                     NA,                    "Perdita trifasciata Timberlake",                      NA,       "FEMALE",                                               NA,              NA,            NA, "GBIF_Andrenidae",        "Perdita trifasciata",       "Perdita trifasciata Timberlake, 1953",           36.876388,           -108.39286,                                90L,              92L,               "High",                      "COTTONWOOD SPRING",              "locality",                   33L,
  "Dorey_data_13971366", "Augochlorella pomoniella (Cockerell, 1915)", "Halictidae", "Halictinae", "Augochlorella",        NA,          NA,   "Augochlorella pomoniella",     "pomoniella",                    NA,                 NA,         NA,       "(Cockerell, 1915)",              NA, "United States",    "United States",         "US",   "California",          "Inyo",            NA,                   "17 mi E Big Pine, Death Valley Road, pinon juniper zone",      NA,                                                   NA,                                                                                                         NA, "1992-06-21T00:00:00Z",  21L,     6L, 1992L,  "PreservedSpecimen",               NA,                NA,            NA,        "M.E. Irwin, D.K. Yeates",       NA,                NA,              NA,               1L, "INHS Insect Collection 352770",            NA,           "INHS",               NA,                NA,         NA,           NA,                   NA,                                                              "3247430",      NA, "urn:uuid:ab6083b7-ad01-4537-a7c4-e1cff7f2172c", "d93d943b-2390-4e2c-9050-11a9ec9a2a96",                                                  NA, "1992-06-21/1992-06-24",       "Female", "http://creativecommons.org/licenses/by-nc/3.0/",              NA,    "58444644", "SCAN_Halictidae",                           NA, "Augochlorella pomoniella (Cockerell, 1915)",           37.142698,          -118.123715,                                90L,             100L,               "High",     "DEATH VALLEY RD AT DEATH VALLEY RD",              "locality",                    2L,
       "CAES_data_4284",       "Andrena wellesleyana Robertson, 1897", "Andrenidae", "Andreninae",       "Andrena",        NA,          NA,       "Andrena wellesleyana",   "wellesleyana",                    NA,                 NA,         NA,         "Robertson, 1897",              NA, "United states",    "United states",         "US",  "Connecticut",     "New Haven",            NA, "North Haven, 0.5 km NNW of interchange 12 (US Highway 5) on Interstate 91",      NA, "https://creativecommons.org/licenses/by-nc-sa/4.0/",                                                                                                         NA, "1998-03-31T00:00:00Z",  31L,     3L, 1998L,                   NA,               NA,                NA,            NA,                 "Chris T. Maier",       NA,         "Netting",              NA,               1L,             "UCMS_ENT 00076127",            NA,           "CAES",               NA,                NA,         NA,           NA,                   NA,                                                                     NA,      NA,                                              NA,                                     NA, "Andrena (Parandrena) wellesleyana Robertson, 1910",                      NA, "Adult Female",                                               NA,              NA,            NA, "CAES_Anthophila",       "Andrena wellesleyana",       "Andrena wellesleyana Robertson, 1897",           41.403421,           -72.853785,                               170L,              89L,               "High",         "Distance NNW of INTERCHANGE 12",              "locality",                    4L,
       "CAES_data_4285",       "Andrena wellesleyana Robertson, 1897", "Andrenidae", "Andreninae",       "Andrena",        NA,          NA,       "Andrena wellesleyana",   "wellesleyana",                    NA,                 NA,         NA,         "Robertson, 1897",              NA, "United states",    "United states",         "US",  "Connecticut",     "New Haven",            NA, "North Haven, 0.5 km NNW of interchange 12 (US Highway 5) on Interstate 91",      NA, "https://creativecommons.org/licenses/by-nc-sa/4.0/",                                                                                                         NA, "1997-04-21T00:00:00Z",  21L,     4L, 1997L,                   NA,               NA,                NA,            NA,                 "Chris T. Maier",       NA,         "Netting",              NA,               1L,             "UCMS_ENT 00076128",            NA,           "CAES",               NA,                NA,         NA,           NA,                   NA,                                                                     NA,      NA,                                              NA,                                     NA, "Andrena (Parandrena) wellesleyana Robertson, 1911",                      NA, "Adult Female",                                               NA,              NA,            NA, "CAES_Anthophila",       "Andrena wellesleyana",       "Andrena wellesleyana Robertson, 1897",           41.403421,           -72.853785,                               170L,              89L,               "High",         "Distance NNW of INTERCHANGE 12",              "locality",                    4L,
   "Dorey_data_1010149", "Acamptopoeum submetallicum (Spinola, 1851)", "Andrenidae", "Panurginae",  "Acamptopoeum",        NA,          NA, "Acamptopoeum submetallicum",  "submetallicum",                    NA,                 NA,  "SPECIES",         "(Spinola, 1851)", "SOUTH_AMERICA",         "Chile",            "Chile",         "CL",        "Maule",         "Talca",            NA,                                                                 "Rio Claro",      NA,                                       "CC_BY_NC_4_0", "OCCURRENCE_STATUS_INFERRED_FROM_INDIVIDUAL_COUNT;INSTITUTION_MATCH_FUZZY;INSTITUTION_COLLECTION_MISMATCH", "1980-11-28T00:00:00Z",  28L,    11L, 1980L, "PRESERVED_SPECIMEN", "PhysicalObject",         "PRESENT",            NA,                               NA,       NA,                NA,              NA,               1L,                          "1291",            NA,           "PUCV",               NA,                NA,         NA,           NA,                   NA,                                                       "PUCV:ENTO:1291",      NA,                                              NA,                                     NA,                        "Acamptopoeum submetallicum",                      NA,       "FEMALE",                                               NA,              NA,            NA, "GBIF_Andrenidae", "Acamptopoeum submetallicum", "Acamptopoeum submetallicum (Spinola, 1851)",          -34.997203,           -70.818563,                               210L,              84L,               "High",                              "RIO CLARO",              "locality",                    4L
  )

testData2 <- tibble::tribble(
                        ~database_id,                            ~scientificname,      ~family,   ~subfamily,         ~genus, ~subgenus, ~infraspecificepithet,         ~specificepithet, ~`_specificepithet`, ~`_infraspecificepithet`, ~acceptednameusage, ~taxonrank, ~scientificnameauthorship, ~unnamed_column_1, ~continent,        ~country, ~country_suggested, ~countrycode,  ~stateprovince,  ~county, ~municipality,                    ~locality, ~island,    ~license,                                                                  ~issue,             ~eventdate, ~day, ~month, ~year,       ~basisofrecord, ~type, ~occurrencestatus, ~recordnumber,   ~recordedby, ~eventid, ~samplingprotocol, ~samplingeffort, ~individualcount,             ~catalognumber, ~rightsholder, ~institutioncode, ~unnamed_column_2, ~decimallatitude, ~decimallongitude, ~unnamed_column_3, ~datasetid, ~datasetname, ~othercatalognumbers,                          ~occurrenceid, ~coreid,                                       ~recordid,                          ~collectionid,                        ~verbatimscientificname, ~verbatimeventdate,     ~sex,                                          ~rights, ~unnamed_column_4, ~occurrenceyear,       ~id,       ~datasource, ~unnamed_column_5,      ~names_clean,                   ~verbatim_scientificname, ~bels_match_country, ~bels_interpreted_countrycode,                  ~bels_matchwithcoords,              ~bels_matchverbatimcoords,                  ~bels_matchsanscoords, ~bels_decimallatitude, ~bels_decimallongitude, ~bels_geodeticdatum, ~bels_coordinateuncertaintyinmeters,   ~bels_georeferencedby, ~bels_georeferenceddate,                                                                        ~bels_georeferenceprotocol,       ~bels_georeferencesources, ~bels_georeferenceremarks, ~bels_georeference_score, ~bels_georeference_source, ~bels_best_of_n_georeferences,              ~bels_match_type,
                "Dorey_data_7221776",              "Augochlora pura (Say, 1837)", "Halictidae", "Halictinae",   "Augochlora",        NA,                    NA,        "Augochlora pura",              "pura",                       NA,                 NA,  "SPECIES",             "(Say, 1837)",                NA,         NA, "United states",    "United states",         "US", "West Virginia",       NA,            NA, "Coopers Rock State Forest,",      NA, "CC_BY_4_0", "TAXON_MATCH_HIGHERRANK;INSTITUTION_MATCH_FUZZY;COLLECTION_MATCH_FUZZY", "1987-08-17T00:00:00Z",  17L,     8L, 1987L, "PRESERVED_SPECIMEN",    NA,         "PRESENT",            NA,            NA,       NA,                NA,              NA,               NA, "Insect Collection 358298",            NA,           "INHS",                NA,               NA,                NA,        436516747L,         NA,           NA,                   NA,                                     NA,      NA,                                              NA,                                     NA, "Augochlora (Augochlora) pura pura (Say 1837)",                 NA,       NA,                                               NA,                NA,              NA,        NA, "GBIF_Halictidae",                NA, "Augochlora pura",              "Augochlora pura (Say, 1837)",                "US",                          "US", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest",             39.664554,             -79.773401,         "epsg:4326",                                  6L,                      NA,                      NA,                                                                                                NA,                              NA,                        NA,                       0L,                    "GBIF",                            2L, "match using verbatim coords",
                "Dorey_data_7242038",              "Augochlora pura (Say, 1837)", "Halictidae", "Halictinae",   "Augochlora",        NA,                    NA,        "Augochlora pura",              "pura",                       NA,                 NA,  "SPECIES",             "(Say, 1837)",                NA,         NA, "United states",    "United states",         "US", "West Virginia",       NA,            NA, "Coopers Rock State Forest,",      NA, "CC_BY_4_0", "TAXON_MATCH_HIGHERRANK;INSTITUTION_MATCH_FUZZY;COLLECTION_MATCH_FUZZY", "1987-08-17T00:00:00Z",  17L,     8L, 1987L, "PRESERVED_SPECIMEN",    NA,         "PRESENT",            NA,            NA,       NA,                NA,              NA,               NA, "Insect Collection 358299",            NA,           "INHS",                NA,               NA,                NA,        436516760L,         NA,           NA,                   NA,                                     NA,      NA,                                              NA,                                     NA, "Augochlora (Augochlora) pura pura (Say 1837)",                 NA,       NA,                                               NA,                NA,              NA,        NA, "GBIF_Halictidae",                NA, "Augochlora pura",              "Augochlora pura (Say, 1837)",                "US",                          "US", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest",             39.664554,             -79.773401,         "epsg:4326",                                  6L,                      NA,                      NA,                                                                                                NA,                              NA,                        NA,                       0L,                    "GBIF",                            2L, "match using verbatim coords",
                "Dorey_data_7220088",              "Augochlora pura (Say, 1837)", "Halictidae", "Halictinae",   "Augochlora",        NA,                    NA,        "Augochlora pura",              "pura",                       NA,                 NA,  "SPECIES",             "(Say, 1837)",                NA,         NA, "United states",    "United states",         "US", "West Virginia",       NA,            NA, "Coopers Rock State Forest,",      NA, "CC_BY_4_0", "TAXON_MATCH_HIGHERRANK;INSTITUTION_MATCH_FUZZY;COLLECTION_MATCH_FUZZY", "1987-08-17T00:00:00Z",  17L,     8L, 1987L, "PRESERVED_SPECIMEN",    NA,         "PRESENT",            NA,            NA,       NA,                NA,              NA,               NA, "Insect Collection 358300",            NA,           "INHS",                NA,               NA,                NA,        436516763L,         NA,           NA,                   NA,                                     NA,      NA,                                              NA,                                     NA, "Augochlora (Augochlora) pura pura (Say 1837)",                 NA,       NA,                                               NA,                NA,              NA,        NA, "GBIF_Halictidae",                NA, "Augochlora pura",              "Augochlora pura (Say, 1837)",                "US",                          "US", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest",             39.664554,             -79.773401,         "epsg:4326",                                  6L,                      NA,                      NA,                                                                                                NA,                              NA,                        NA,                       0L,                    "GBIF",                            2L, "match using verbatim coords",
                "Dorey_data_7236978",              "Augochlora pura (Say, 1837)", "Halictidae", "Halictinae",   "Augochlora",        NA,                    NA,        "Augochlora pura",              "pura",                       NA,                 NA,  "SPECIES",             "(Say, 1837)",                NA,         NA, "United states",    "United states",         "US", "West Virginia",       NA,            NA, "Coopers Rock State Forest,",      NA, "CC_BY_4_0", "TAXON_MATCH_HIGHERRANK;INSTITUTION_MATCH_FUZZY;COLLECTION_MATCH_FUZZY", "1987-08-17T00:00:00Z",  17L,     8L, 1987L, "PRESERVED_SPECIMEN",    NA,         "PRESENT",            NA,            NA,       NA,                NA,              NA,               NA, "Insect Collection 358301",            NA,           "INHS",                NA,               NA,                NA,        436516766L,         NA,           NA,                   NA,                                     NA,      NA,                                              NA,                                     NA, "Augochlora (Augochlora) pura pura (Say 1837)",                 NA,       NA,                                               NA,                NA,              NA,        NA, "GBIF_Halictidae",                NA, "Augochlora pura",              "Augochlora pura (Say, 1837)",                "US",                          "US", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest", "uswestvirginiacoopersrockstateforest",             39.664554,             -79.773401,         "epsg:4326",                                  6L,                      NA,                      NA,                                                                                                NA,                              NA,                        NA,                       0L,                    "GBIF",                            2L, "match using verbatim coords",
               "Dorey_data_15031296", "Lasioglossum sisymbrii (Cockerell, 1895)", "Halictidae", "Halictinae", "Lasioglossum",        NA,                    NA, "Lasioglossum sisymbrii",         "sisymbrii",                       NA,                 NA,         NA,       "(Cockerell, 1895)",                NA,         NA, "United states",    "United states",         "US",       "Arizona", "Mohave",            NA,                     "Topock",      NA,          NA,                                                                      NA, "1972-04-08T00:00:00Z",   8L,     4L, 1972L,  "PreservedSpecimen",    NA,                NA,            NA, "B. Apperson",       NA,                NA,              NA,               1L,                "HYM 95971",         "MNA",            "MNA",                NA,               NA,                NA,                NA,         NA,           NA,                   NA, "1154c20d-211a-47ba-8320-784b8e320e6f",      NA, "urn:uuid:ada6a97d-7d8e-4765-a607-289b4abcaa39", "48b700e0-fcdb-4196-b642-70fd7b8a71ef",                                             NA,         "8/4/1972", "Female", "http://creativecommons.org/licenses/by-nc/4.0/",                NA,              NA, 57139867L, "SCAN_Halictidae",                NA,                NA, "Lasioglossum sisymbrii (Cockerell, 1895)",                "US",                          "US",                "usarizonamohavetopock",                "usarizonamohavetopock",                "usarizonamohavetopock",            34.7183075,           -114.4871902,         "epsg:4326",                                 14L, "Gary W. Shugart (PSM)",              "3/8/2003", "MaNIS/HerpNET/ORNIS Georeferencing Guidelines, Guide to Best Practices for Georeferencing 2006.", "AZ GNIS downloaded March 2003",                        NA,                      30L,                   "ORNIS",                            1L, "match using verbatim coords"
               )


# Be sure that the testData is not already in tempdir
testDataPath <- file.info(list.files(tempdir(), full.names = T, 
                                     pattern = "testData.xlsx", recursive = TRUE))
unlink(rownames(testDataPath))

# Save a temporary version of these data
  # First create a workbook
wb <- openxlsx::createWorkbook()
  # Add sheets to it
openxlsx::addWorksheet(wb, "GEOLOCATE HIGH")
openxlsx::addWorksheet(wb, "BELS High")
  # Fill those sheets with data
openxlsx::writeData(wb, "GEOLOCATE HIGH", testData)
openxlsx::writeData(wb, "BELS High", testData2)
  # Save to file
openxlsx::saveWorkbook(wb, file = paste0(tempdir(), "/testData.xlsx"), overwrite = TRUE)


testOut1 <- BeeDC::readr_GeoL(path = paste0(tempdir()),
                              inFile = "/testData.xlsx",
                              outFile = "testDataOut.csv",
                              dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")



# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)

# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_GeoL results columns TRUE", {
  testthat::expect_equal(resultsT, 59)
})
testthat::test_that("readr_GeoL results columns FALSE", {
  testthat::expect_equal(resultsF, 1)
})

testthat::test_that("readr_GeoL expected class", {
  testthat::expect_type(testOut1, "list")
})



