requireNamespace("readr")
requireNamespace("BeeDC")
requireNamespace("dplyr")
requireNamespace("openxlsx")

library(dplyr) ## could not use %>% without loading as library

testData <- dplyr::tribble(
     ~Catalognumber, ~institutionCode, ~collectionCode, ~ownerInstitutionCode,                          ~collectionID,      ~basisOfRecord,                          ~occurrenceID, ~catalogNumber, ~otherCatalogNumbers,                                                                                           ~higherClassification,   ~kingdom,      ~phylum,    ~class,        ~order,  ~family,       ~scientificName, ~taxonID, ~scientificNameAuthorship,     ~genus, ~subgenus, ~specificEpithet, ~verbatimTaxonRank, ~infraspecificEpithet, ~taxonRank,  ~identifiedBy, ~dateIdentified, ~identificationReferences, ~identificationRemarks, ~taxonRemarks, ~identificationQualifier, ~typeStatus,      ~recordedBy, ~recordNumber, ~eventDate, ~year, ~month, ~day, ~startDayOfYear, ~endDayOfYear, ~verbatimEventDate,                                                                                                ~occurrenceRemarks, ~habitat, ~fieldNumber, ~eventID, ~informationWithheld, ~dataGeneralizations, ~dynamicProperties, ~associatedOccurrences, ~associatedSequences, ~associatedTaxa, ~reproductiveCondition, ~establishmentMeans, ~lifeStage, ~sex, ~individualCount, ~preparations, ~locationID, ~continent, ~waterBody, ~islandGroup, ~island,        ~country,     ~stateProvince, ~county, ~municipality,        ~locality, ~locationRemarks, ~decimalLatitude, ~decimalLongitude, ~geodeticDatum, ~coordinateUncertaintyInMeters,  ~verbatimCoordinates, ~georeferencedBy, ~georeferenceProtocol, ~georeferenceSources, ~georeferenceVerificationStatus, ~georeferenceRemarks, ~minimumElevationInMeters, ~maximumElevationInMeters, ~minimumDepthInMeters, ~maximumDepthInMeters, ~verbatimDepth, ~verbatimElevation, ~disposition, ~language, ~recordEnteredBy,      ~modified,                                             ~rights, ~rightsHolder, ~accessRights,                              ~recordID,                                                                  ~references,
            911208L,      "Field-Obs",    "Entomology",                    NA, "6e16d724-0be0-4101-a230-b841ebd1f0a5", "PreservedSpecimen", "48739ca8-e401-43c2-b52a-137ad191d726",             NA,                   NA, "Organism|Animalia|Arthropoda|Insecta|Pterygota|Hymenoptera|Apocrita|Apoidea|Apidae|Apinae|Euglossini|Euglossa", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae", "Euglossa allosticta",   48972L,             "Moure, 1969", "Euglossa",        NA,     "allosticta",                 NA,                    NA,  "Species", "David Roubik",              NA,                        NA,                     NA,            NA,                       NA,          NA,   "David Roubik",            NA,   "2/2/06", 2006L,     2L,   2L,             33L,            NA,                 NA,                                   "Euglossa allosticta; Euglossa allosticta, Face. Taken with Automontage system",       NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,         NA,   NA,               NA,            NA,          NA,         NA,         NA,           NA,      NA, "French Guiana",                 NA,      NA,            NA,               NA,               NA,               NA,                NA,             NA,                             NA,                    NA,               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "1/8/15 11:31", "http://creativecommons.org/publicdomain/zero/1.0/",            NA,            NA, "62e76208-6975-43ae-b805-5f02766fc9ce", "https://panamabiota.org/stri/collections/individual/index.php?occid=911208",
            911091L,      "Field-Obs",    "Entomology",                    NA, "6e16d724-0be0-4101-a230-b841ebd1f0a5", "PreservedSpecimen", "a4e323b1-f79d-4826-86ba-26c00c7ba7ea",             NA,                   NA,  "Organism|Animalia|Arthropoda|Insecta|Pterygota|Hymenoptera|Apocrita|Apoidea|Apidae|Apinae|Meliponini|Trigona", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",    "Trigona amalthea",   55214L,         "(Olivier, 1789)",  "Trigona",        NA,       "amalthea",                 NA,                    NA,  "Species",             NA,              NA,                        NA,                     NA,            NA,                       NA,          NA, "Miriam Arrueta",            NA,         NA,    NA,     NA,   NA,              NA,            NA,                 NA,  "Orchid Bee: Trigona amalthea; David Roubik Cerro Brewster Orchid Bee collection: Trigona amalthea, Dorsal view",       NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,         NA,   NA,               NA,            NA,          NA,         NA,         NA,           NA,      NA,        "PANAMA",         "SAN BLAS",      NA,            NA, "CERRO BREWSTER",               NA,         9.370558,        -79.247071,             NA,                             NA, "17 692500E 1036300N",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "1/8/15 11:31", "http://creativecommons.org/publicdomain/zero/1.0/",            NA,            NA, "2c2a5b65-de7d-4ceb-9445-ada9fcfbb7ad", "https://panamabiota.org/stri/collections/individual/index.php?occid=911091",
            911092L,      "Field-Obs",    "Entomology",                    NA, "6e16d724-0be0-4101-a230-b841ebd1f0a5", "PreservedSpecimen", "9e7a88c2-09be-4b9c-b59b-f458ea424800",             NA,                   NA,  "Organism|Animalia|Arthropoda|Insecta|Pterygota|Hymenoptera|Apocrita|Apoidea|Apidae|Apinae|Meliponini|Trigona", "Animalia", "Arthropoda", "Insecta", "Hymenoptera", "Apidae",    "Trigona amalthea",   55214L,         "(Olivier, 1789)",  "Trigona",        NA,       "amalthea",                 NA,                    NA,  "Species",             NA,              NA,                        NA,                     NA,            NA,                       NA,          NA, "Miriam Arrueta",            NA,         NA,    NA,     NA,   NA,              NA,            NA,                 NA, "Orchid Bee: Trigona amalthea; David Roubik Cerro Brewster Orchid Bee collection: Trigona amalthea, Oblique view",       NA,           NA,       NA,                   NA,                   NA,                 NA,                     NA,                   NA,              NA,                     NA,                  NA,         NA,   NA,               NA,            NA,          NA,         NA,         NA,           NA,      NA,        "PANAMA", "SAN BLAS (KUNA Y",      NA,            NA, "CERRO BREWSTER",               NA,         9.370558,        -79.247071,             NA,                             NA, "17 692500E 1036300N",               NA,                    NA,                   NA,                              NA,                   NA,                        NA,                        NA,                    NA,                    NA,             NA,                 NA,           NA,        NA,               NA, "1/8/15 11:31", "http://creativecommons.org/publicdomain/zero/1.0/",            NA,            NA, "29b950c2-4d7b-423b-aba1-ea96ccba523b", "https://panamabiota.org/stri/collections/individual/index.php?occid=911092"
)


# Be sure that the testData is not already in tempdir
testDataPath <- file.info(list.files(tempdir(), full.names = T, 
                                     pattern = "testData.csv", recursive = TRUE))
unlink(rownames(testDataPath))

# Save a temporary version of these data
readr::write_csv(testData, paste0(tempdir(), "/testData.csv"))

testOut1 <- BeeDC::readr_BeeDC(dataset = "STRI",
                               path = tempdir(),
                               inFile = "testData.csv",
                               outFile = "testDataOut.csv",
                               dataLicense = "https://creativecommons.org/licenses/by-nc-sa/4.0/")


# Get a count of TRUE and FALSE column name matches
resultsT <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == TRUE)
resultsF <- sum(colnames(testOut1) %in% (BeeDC::ColTypeR()[[1]] %>% names()) == FALSE)

# Test the number of expected TRUE and FALSE columns and then test the output format (data frames and
# tibbles are a special case of lists)
testthat::test_that("readr_STRI results columns TRUE", {
  testthat::expect_equal(resultsT, 60)
})
testthat::test_that("readr_STRI results columns FALSE", {
  testthat::expect_equal(resultsF, 39)
})

testthat::test_that("readr_STRI expected class", {
  testthat::expect_type(testOut1, "list")
})
