# This function was written on the 25th of February to find manually identified outliers in 
  # bee data
# For questions, contact JAmes B Dorey at jbdorey@me.com


manualOutlierFindeR <- function(
    occData = NULL,
    DataPath = NULL,
    PaigeOutliersName = "removedBecauseDeterminedOutlier.csv",
    newOutliersName = "All_outliers_ANB.xlsx",
    ColombiaOutliers_all = "All_Colombian_OutlierIDs.csv",
    duplicates = NULL
    ){
  
  #### 0.0 Prep ####
  ##### 0.1 Errors ####
  ###### a. FATAL errors ####
  if(is.null(occData)){
    stop(paste0(" — No occData was given. Please specify the occurrence data."))
  }
  if(is.null(DataPath)){
    stop(paste0(" — No DataPath was given. Please specify the directory that contains the outliers."))
  }
  if(is.null(PaigeOutliersName)){
    stop(paste0(" — No PaigeOutliersName was given. Please specify the outliers' file name."))
  }
  if(is.null(newOutliersName)){
    stop(paste0(" — No newOutliersName was given. Please specify the outliers' file name."))
  }
  if(is.null(duplicates)){
    stop(paste0(" — No duplicates was given. Please provide the duplicates dataset as generated by jbd_dupeSummary."))
  }
  ###
  
  #### 1.0 Data prep ####
    ##### 1.1 Find data ####
  writeLines(" — Looking for the datasets...")
      ###### a. Paige outliers ####
  # Find the outliers from chesshire et al. 2023
  PaigeOutliers <- file_finder(path = DataPath,
                               file = PaigeOutliersName) %>%
    readr::read_csv( col_types = ColTypeR()) %>%
    suppressWarnings()
  
      ###### b. new outliers ####
  # Find the new outliers from the three sheets concatenates by Angela
  outliersAll <- file_finder(path = DataPath,
                             file = newOutliersName) %>%
    readxl::read_xlsx("Outliers_FromCanadaToPanama_ANB", col_types = "text") %>%
    dplyr::bind_rows(file_finder(path = DataPath,
                                 file = newOutliersName) %>%
                       readxl::read_xlsx("Tracys_outliers", col_types = "text")) %>%
    dplyr::bind_rows(file_finder(path = DataPath,
                                 file = newOutliersName) %>%
                       readxl::read_xlsx("Colombian_outliers", col_types = "text")) %>%
    dplyr::bind_rows(file_finder(path = DataPath,
                                 file = newOutliersName) %>%
                       readxl::read_xlsx("Outliers_SppInStatus3", col_types = "text")) %>%
    readr::write_csv(paste(OutPath_Report, "newOutliers.csv", sep = "/"))
  # Read back in with the correct column classes
  outliersAll <- file_finder(path = DataPath,
                             file = "newOutliers.csv") %>%
    readr::read_csv(col_types = ColTypeR()) %>%
    dplyr::mutate(eventDate = eventDate %>%
                    lubridate::ymd_hms(truncated = 5)) %>%
    suppressWarnings()
  
  ###### c. Colombia ####
  ColombiaOutliers <- file_finder(path = DataPath,
                               file = ColombiaOutliers_all) %>%
    readr::read_csv( col_types = ColTypeR()) %>%
    suppressWarnings()
  
  ###### d. eventDate ####
    # format occData eventDate
  occData <- occData %>%
    dplyr::mutate(eventDate = eventDate %>%
                    lubridate::ymd_hms(truncated = 5))
  
  
    ##### 1.2 Process Paige ####
  writeLines(" — Processing the Paige outliers...")
  
  # Find PaigeOutliers in the occurrence data by occurrenceID and institutionCode
  Outl_occID <- occData %>%
    tidyr::drop_na(occurrenceID) %>%
    dplyr::filter(occurrenceID %in% PaigeOutliers$occurrenceID &
                    institutionCode %in% PaigeOutliers$institutionCode) 
  # Find PaigeOutliers by occurrenceID and institutionCode
  Outliers_matched <- occData %>%
    # Remove matched IDs
    dplyr::filter(!occurrenceID %in% Outl_occID$occurrenceID) %>%
    tidyr::drop_na(catalogNumber, institutionCode) %>%
    dplyr::filter(catalogNumber %in% PaigeOutliers$catalogNumber &
                    institutionCode %in% PaigeOutliers$institutionCode) %>%
    # Re-bind the outlier matches 
    dplyr::bind_rows(Outl_occID)

  # Combine the Paige and new outliers 
  outliersAll <- outliersAll %>%
    dplyr::bind_rows(Outliers_matched) 
  
  #### 2.0 Find outlier duplicates ####
    ##### 2.1 Find duplicates ####
  writeLines(" — Looking for duplicates of the outliers...")
    # Get a list of the outliers and their duplicates
  outlierDuplicates <- duplicates %>%
    dplyr::filter(database_id %in% outliersAll$database_id | 
                    database_id_keep %in% outliersAll$database_id)
  duplicateList <- c(outlierDuplicates %>% dplyr::pull(database_id), 
                     outlierDuplicates %>% dplyr::pull(database_id_keep)) %>% unique()
  
    ##### 2.2 Combine duplicates ####
  # Get a list of all outliers and their duplicates — database_id
  outList <- c(outliersAll %>% dplyr::pull(database_id), duplicateList,
               ColombiaOutliers %>% pull(database_id)) %>% unique()
  
  #### 3.0 Flag records ####
  # Find the occurrences that did not match
  occData <- occData %>%
    # Add the .expertOutlier columns as TRUE (not flagged)
    dplyr::mutate(.expertOutlier = dplyr::if_else(
      database_id %in% outList,
      FALSE, TRUE)) 
  # Return user output
  message(
    paste(
      "\\manualOutlierFindeR:\n",
      "Flagged",
      format(sum(occData$.expertOutlier == FALSE, na.rm = TRUE), big.mark = ","),
      "expert-identified outliers:\n",
      "The column '.expertOutlier' was added to the database.\n"
    )
  )
  
  # Return data
return(occData)
  
}

