---
title: "Data news"

output:
  rmarkdown::html_vignette:
  
vignette: >
  %\VignetteIndexEntry{Data news}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data updates

Here I will try to manage a list of data updates and the over-arching changes in the datasets. These changes are commensurate with those in the "Package news" section where changes of functions within **BeeBDC** themselves are documented.

## Bees taxonomy

The bee taxonomy files have been changed as below. Most changes represent a new pull from Discover Life and most also represent new manual additions due to mistakes, missing names, changes on Discover Life, or recent taxonomic revisions.

- 2026-07-09 **current**: <https://api.figshare.com/v2/file/download/66453893>

  - This version fixes an issue where not all names on Discover Life are separated by the usual delimiter and so not all synonyms are recognised. Additionally, recent Australian revisions by Leijs and Walker are included in addition to the new Discover Life pull. This is a major improvement on the prior version.

- 2026-05-04: <https://api.figshare.com/v2/file/download/64193731>

- 2026-01-12: <https://open.flinders.edu.au/ndownloader/files/60945820>

- 2024-06-17: <https://open.flinders.edu.au/ndownloader/files/47089969>

- 2023-11-29: <https://open.flinders.edu.au/ndownloader/files/43331472>

- 2023-10-10: <https://open.flinders.edu.au/ndownloader/files/42613126>

- 2023-09-20: <https://open.flinders.edu.au/ndownloader/files/42402264>

- Original: <https://open.flinders.edu.au/ndownloader/files/42320595>

## Bees checklist

The updated checklist files represent new pulls from Discover Life.

- 2026-01-12 **current**: <https://open.flinders.edu.au/ndownloader/files/60945823>

- 2024-06-17: <https://open.flinders.edu.au/ndownloader/files/47092720>

- Original: <https://open.flinders.edu.au/ndownloader/files/42320598>

## Bee occurrence dataset

The bee occurrence dataset has ended up being updated least frequently. This is in part because it takes this longest and because I prioritise updating the package and allowing researchers to use the datasets and functions as they see fit. This is, however, naive as many researchers will simply take the dateset provided and run with it. There are known issues with the dataset version and, thanks to Zach Portman, it has been pointed out that these should be made more obvious and documented. This may not be perfect documentation but major issues are highlighted below.

### Clean and unclean datasets

- Upcoming version...

  - A completely new 2026 pull is in the making...

- *Version 1.3.4 runs of early data — 05_cleaned_database_2023v1_3_3.csv.zip* and *05_unCleaned_database_2023v1_3_3.csv.zip —* This new run of an early dataset from start to finish using BeeBDC version 1.3.4 has the following changes:

  - Now has 19,890,804 rows of data (uncleaned).

  - Has the below taxonomic issues fixed. However, this process has highlighted that some names are not formatting correctly from the Discover Life taxonomy (bee taxonomy version 2026-05-04) and will be updated in BeeBDC 1.4.0 or before.

  - Better matches from `BeeBDC::jbd_coordCountryInconsistent()` and `BeeBDC::dateFindR()`.

  - `BeeBDC::harmoniseR()` now matches names in the verbatimScientificName column if there is no match from the scientificName column.

  - Addition of flags from `BeeBDC::continentOutlieRs()`.

  - `BeeBDC::flagAbsent()` also now checks if *individualCount == 0*.

<!-- -->

- *05_cleaned_database_2024-02-15.csv.zip* and *05_unCleaned_database_2024-02-15.csv.zip*

  - Both of these datasets have an issue with 27 names where names were "successfully" matched to genus/subgenus-level taxa (this mostly applies to species-level names). This was a problem that was fixed in BeeBDC's Bee taxonomy list from version 1.0.2. However, it was perpetuated because I re-ran the dataset thinking to fix it, but needed to run it from an earlier step, rather than just over the top of the original data versions. Hence, the problems persisted. The problem names are as below and are over-applied in the dataset are in the table below. Note, that these numbers are generated comparing the v1_3_3 data which has 19,890,804 rows (about a million more). Please consider using those datasets, where these issues are removed.

    | **scientificName** | **Additional false records (v1_3_3 data)** |
    |-----------------------------------------|-------------------------------|
    | *Andrena* *columbiana* Viereck, 1917 | 21,217 |
    | *Andrena* Fabricius, 1775 | 20,050 |
    | *Apis* *mellifera* Linnaeus, 1758 | 5,151 |
    | *Bombus* *hypnorum* (Linnaeus, 1758) | 87,703 |
    | *Coelioxys* *texanus* Cresson, 1872 | 7,681 |
    | *Colletes* *kincaidii* Cockerell, 1898 | 25,953 |
    | *Colletes* Latreille, 1802 | 13,398 |
    | *Dasypoda argentata* Panzer, 1809 | 99 |
    | *Dufourea longispinis* (Wu, 1987) | 8 |
    | *Euglossa macrorhyncha* Dressler, 1982 | 6,273 |
    | *Halictus* | 16,199 |
    | *Halictus Latreille*, 1804 | 4,847 |
    | *Halictus simplex* Blüthgen, 1923 | 45,594 |
    | *Lasioglossum albipenne* (Robertson, 1890) | 179,682 |
    | *Lasioglossum* Curtis, 1833 | 50,920 |
    | *Leioproctus boroniae* (Cockerell, 1921) | 2 |
    | *Leioproctus leai* (Cockerell, 1913) | 26,794 |
    | *Leioproctus michenerianus* (E. A. B. Almeida, 2008) | 4 |
    | *Macropis steironematis* Robertson, 1891 | 41 |
    | *Megachile brevis* Say, 1837 | 32,603 |
    | *Megachile Latreille*, 1802 | 16,884 |
    | *Melecta diligens* Lieftinck, 1983 | 484 |
    | *Melissodes microstictus* Cockerell, 1905 | 38,447 |
    | *Osmia coloradensis* Cresson, 1878 | 20,262 |
    | *Osmia Panzer*, 1806 | 8,201 |
    | *Perditomorpha arnaui* Moure, 1954 | 55 |
    | *Xylocopa virginica* (Linnaeus, 1771) | 20,270 |

  - Download links:

    - [*05_cleaned_database_2024-02-15.csv.zip*](https://open.flinders.edu.au/ndownloader/files/44554373)

    - [*05_unCleaned_database_2024-02-15.csv.zip*](https://open.flinders.edu.au/ndownloader/files/44554382)
